### PR TITLE
fix(account): Fields Not Included in JSON Body are Reset to Empty or Null During Update

### PR DESCRIPTION
**Pull request by awalnur**
When updating an account, only the field present in the JSON request body will be updated in the database. Fields not included in the JSON body will not be changed.

## Summary by CodeRabbit

- **New Features**
	- Enhanced account update functionality to prevent overwriting existing `FullName` and `Email` with empty values.

- **Bug Fixes**
	- Improved robustness of the account update operation by validating input before applying changes.

### CODE REVIEW

**Review by arifai — CHANGES_REQUESTED** [review]
I don't know the `ValidateBody` method can't work.

https://github.com/arifai/zenith/blob/7d84f877194c62435225f18629eebb47da12407f/internal/account/api/handler/handler.go#L123-L130

Screenshot 2024-09-16 at 22 44 06

**Comment by arifai** [comment]
This PR is conflicts, please resolve it.

**Comment by geekswamp** [comment]
close

**Pull request closed without merging**
